apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k6-pvc
  labels:
    app: k6
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [k6]}
