apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
stringData:
  POSTGRES_DB: prod
  POSTGRES_USER: internal
  POSTGRES_PASSWORD: VeUArS1hCeHkT0ObdBlZBDKTou9jG8cDYK1ZlwdlB8dx
  POSTGRES_HOST: database-service.default.svc.cluster.local
