apiVersion: v1
kind: Service
metadata:
  name: ot-service
  labels:
    app: ot
spec:
  type: ClusterIP
  ports:
    - port: 4317
      name: collector-grpc-svc
      targetPort: 4317
    - port: 4318
      name: collector-http-svc
      targetPort: 4318
  selector:
    app.kubernetes.io/name: opentelemetry-collector
