apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-service-reader
  namespace: default
rules:
- apiGroups: [""] 
  resources: ["pods", "services", "endpoints", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "watch", "list"]